name: KTB Product Crawl

on:
  schedule:
    - cron: "*/5 0-16 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ----- BƯỚC GỠ LỖI 1: KIỂM TRA TRẠNG THÁI BAN ĐẦU -----
      - name: Log initial state of last_file.txt
        run: |
          echo "--- Checking state of last_file.txt BEFORE python script runs ---"
          # Lệnh '|| true' để không bị lỗi nếu file chưa tồn tại
          ls -l last_file.txt || true
          echo "--- File content BEFORE: ---"
          cat last_file.txt || echo "last_file.txt does not exist yet."
          echo "--------------------------------"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run crawler
        run: python crawler.py

      # ----- BƯỚC GỠ LỖI 2: KIỂM TRA TRẠNG THÁI SAU KHI CHẠY -----
      - name: Log state after crawler script
        run: |
          echo "--- Checking state of last_file.txt AFTER python script ran ---"
          ls -l last_file.txt
          echo "--- File content AFTER: ---"
          cat last_file.txt
          echo "-------------------------------"

      - name: Check for meaningful changes (new URLs > 0)
        id: check_meaningful_changes
        run: |
          echo "Checking content of last_file.txt for new URLs..."
          if grep -E -q '[1-9][0-9]* new URLs added' last_file.txt; then
            echo "Meaningful changes detected (new URLs found)."
            echo "has_new_urls=true" >> "$GITHUB_OUTPUT"
          else
            echo "No new URLs found. All are '0 new URLs added'."
            echo "has_new_urls=false" >> "$GITHUB_OUTPUT"
          fi

      # ... Các bước còn lại giữ nguyên ...
      - name: Check status and trigger image-crawler if idle
        if: steps.check_meaningful_changes.outputs.has_new_urls == 'true'
        id: trigger_dispatch
        env:
          GH_TOKEN: ${{ secrets.KTBIHOW_PAT }}
          TARGET_OWNER: 'ktbihow'
          TARGET_REPO: 'image-crawler'
          TARGET_WORKFLOW: 'crawler-image.yml'
        run: |
          echo "Triggering image-crawler..."
          # (Logic kiểm tra và trigger giữ nguyên)
          in_progress_runs=$(gh run list --repo "${TARGET_OWNER}/${TARGET_REPO}" --workflow "${TARGET_WORKFLOW}" --status "in_progress" --status "queued" --limit 1 --json databaseId)
          if [[ "$in_progress_runs" != "[]" ]]; then
            echo "Target workflow is busy. Skipping trigger."
            echo "triggered=skipped" >> "$GITHUB_OUTPUT"
            echo "reason=Target workflow is busy" >> "$GITHUB_OUTPUT"
          else
            echo "Target workflow is idle. Triggering now..."
            gh api --method POST -H "Accept: application/vnd.github+json" "/repos/${TARGET_OWNER}/${TARGET_REPO}/dispatches" -f event_type='new_product_available'
            echo "Trigger dispatch sent successfully."
            echo "triggered=sent" >> "$GITHUB_OUTPUT"
            echo "reason=New URLs available" >> "$GITHUB_OUTPUT"
          fi

      - name: Send Log Content to Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          LOG_CONTENT=$(cat last_file.txt)
          TRUNCATED_LOG=$(echo "$LOG_CONTENT" | head -c 4000)
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage -d chat_id=$TELEGRAM_CHAT_ID -d text="$TRUNCATED_LOG" || echo "Lỗi khi gửi nội dung log!"

      - name: Send Success Message to Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ KTB Product Crawl - Done
            New URLs found: ${{ steps.check_meaningful_changes.outputs.has_new_urls }}
            Trigger status: ${{ steps.trigger_dispatch.outputs.triggered }} (${{ steps.trigger_dispatch.outputs.reason }})

      - name: Send Failure Message to Telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "❌ KTB Product Crawl - Fail."
          
      - name: Commit & push results
        run: |
          git add last_file.txt
          if ! git diff --staged --quiet; then
            echo "Committing changes..."
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "Update URLs with new products [skip ci]"
            git push
          else
            echo "No file changes to commit."
          fi
