name: KTB Product Crawl

on:
  schedule:
    - cron: "*/5 0-16 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run crawler
        run: python crawler.py

      # ----- LOGIC KIỂM TRA ĐÃ ĐƯỢC THAY THẾ -----
      - name: Check for meaningful changes (new URLs > 0)
        id: check_meaningful_changes # Đổi ID để rõ ràng hơn
        run: |
          echo "Checking content of last_file.txt for new URLs..."
          # Dùng grep để tìm các dòng có dạng "X new URLs added" với X là số từ 1-9 trở lên
          # grep -E: Bật chế độ regular expression mở rộng
          # '[1-9][0-9]* new URLs added': Mẫu tìm kiếm
          #   [1-9]: Ký tự đầu tiên phải là số từ 1 đến 9
          #   [0-9]*: Theo sau là 0 hoặc nhiều ký tự số từ 0 đến 9
          # cờ -q (quiet): grep sẽ thoát ngay khi tìm thấy dòng đầu tiên và không in ra màn hình
          if grep -E -q '[1-9][0-9]* new URLs added' last_file.txt; then
            echo "Meaningful changes detected (new URLs found)."
            echo "has_new_urls=true" >> "$GITHUB_OUTPUT"
          else
            echo "No new URLs found. All are '0 new URLs added'."
            echo "has_new_urls=false" >> "$GITHUB_OUTPUT"
          fi

      # ----- KẾT THÚC THAY ĐỔI LOGIC KIỂM TRA -----

      - name: Check status and trigger image-crawler if idle
        # Chỉ chạy khi bước trên xác định là CÓ URL MỚI
        if: steps.check_meaningful_changes.outputs.has_new_urls == 'true'
        id: trigger_dispatch
        env:
          GH_TOKEN: ${{ secrets.KTBIHOW_PAT }}
          TARGET_OWNER: 'ktbihow'
          TARGET_REPO: 'image-crawler'
          TARGET_WORKFLOW: 'crawler-image.yml'
        run: |
          echo "Checking status of '${TARGET_WORKFLOW}' in ${TARGET_OWNER}/${TARGET_REPO}..."
          
          in_progress_runs=$(gh run list \
            --repo "${TARGET_OWNER}/${TARGET_REPO}" \
            --workflow "${TARGET_WORKFLOW}" \
            --status "in_progress" \
            --status "queued" \
            --limit 1 \
            --json databaseId)

          if [[ "$in_progress_runs" != "[]" ]]; then
            echo "Target workflow is busy. Skipping trigger."
            echo "triggered=skipped" >> "$GITHUB_OUTPUT"
            echo "reason=Target workflow is busy" >> "$GITHUB_OUTPUT"
          else
            echo "Target workflow is idle. Triggering now..."
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              "/repos/${TARGET_OWNER}/${TARGET_REPO}/dispatches" \
              -f event_type='new_product_available'
            echo "Trigger dispatch sent successfully."
            echo "triggered=sent" >> "$GITHUB_OUTPUT"
            echo "reason=New URLs available" >> "$GITHUB_OUTPUT"
          fi

      - name: Send Log Content to Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          LOG_CONTENT=$(cat last_file.txt)
          TRUNCATED_LOG=$(echo "$LOG_CONTENT" | head -c 4000)
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="$TRUNCATED_LOG" || echo "Lỗi khi gửi nội dung log!"

      - name: Send Success Message to Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ KTB Product Crawl - Done
            New URLs found: ${{ steps.check_meaningful_changes.outputs.has_new_urls }}
            Trigger status: ${{ steps.trigger_dispatch.outputs.triggered }} (${{ steps.trigger_dispatch.outputs.reason }})

      - name: Send Failure Message to Telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "❌ KTB Product Crawl - Fail."
          
      - name: Commit & push results
        # Chỉ commit khi có sự thay đổi thực sự
        run: |
          # Kiểm tra lại xem file có thay đổi so với commit cuối không để tránh commit rỗng
          git add last_file.txt
          if ! git diff --staged --quiet; then
            echo "Committing changes..."
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "Update URLs with new products [skip ci]"
            git push
          else
            echo "No file changes to commit."
          fi
